mod 'boxen',    '3.11.0', :github_tarball => 'boxen/puppet-boxen'
mod 'homebrew', '1.13.0', :github_tarball => 'boxen/puppet-homebrew'
mod 'stdlib',   '4.9.0',  :github_tarball => 'puppetlabs/puppetlabs-stdlib'
